In [13]:
import os
import pandas as pd
#print(os.getcwd())
p1=os.path.join(os.getcwd(),"pokemon_data.csv")
print(p1)
df=pd.read_csv(p1)
#print(df)
print(df.iloc[0:4])

/mnt/c/cyperf_automation_new/cyperf/utils/rest_api_wrapper/test_results/pokemon_data.csv
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False

In [16]:
print(df[df['Type 2'] == "Poison"] )

       #                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65
1      2                Ivysaur  Grass  Poison   60      62       63       80
2      3               Venusaur  Grass  Poison   80      82       83      100
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122
16    13                 Weedle    Bug  Poison   40      35       30       20
17    14                 Kakuna    Bug  Poison   45      25       50       25
18    15               Beedrill    Bug  Poison   65      90       40       45
19    15  BeedrillMega Beedrill    Bug  Poison   65     150       40       15
48    43                 Oddish  Grass  Poison   45      50       55       75
49    44                  Gloom  Grass  Poison   60      65       70       85
50    45              Vileplume  Grass  Poison   75      80       85      110
53    48                Venonat    Bug  Poison   60      55       50       40
54    49               Venomoth    Bug  Poison   70      65       60       90
75    69             Bellsprout  Grass  Poison   50      75       35       70
76    70             Weepinbell  Grass  Poison   65      90       50       85
77    71             Victreebel  Grass  Poison   80     105       65      100
78    72              Tentacool  Water  Poison   40      40       35       50
79    73             Tentacruel  Water  Poison   80      70       65       80
99    92                 Gastly  Ghost  Poison   30      35       30      100
100   93                Haunter  Ghost  Poison   45      50       45      115
101   94                 Gengar  Ghost  Poison   60      65       60      130
102   94      GengarMega Gengar  Ghost  Poison   60      65       80      170
181  167               Spinarak    Bug  Poison   40      60       40       40
182  168                Ariados    Bug  Poison   70      90       70       60
227  211               Qwilfish  Water  Poison   65      95       75       55
292  269                 Dustox    Bug  Poison   60      50       70       50
344  315                Roselia  Grass  Poison   50      60       45      100
451  406                  Budew  Grass  Poison   40      30       35       50
452  407               Roserade  Grass  Poison   60      70       65      125
603  543               Venipede    Bug  Poison   30      45       59       30
604  544             Whirlipede    Bug  Poison   40      55       99       40
605  545              Scolipede    Bug  Poison   60     100       89       55
651  590                Foongus  Grass  Poison   69      55       45       55
652  591              Amoonguss  Grass  Poison  114      85       70       85

     Sp. Def  Speed  Generation  Legendary
0         65     45           1      False
1         80     60           1      False
2        100     80           1      False
3        120     80           1      False
16        20     50           1      False
17        25     35           1      False
18        80     75           1      False
19        80    145           1      False
48        65     30           1      False
49        75     40           1      False
50        90     50           1      False
53        55     45           1      False
54        75     90           1      False
75        30     40           1      False
76        45     55           1      False
77        70     70           1      False
78       100     70           1      False
79       120    100           1      False
99        35     80           1      False
100       55     95           1      False
101       75    110           1      False
102       95    130           1      False
181       40     30           2      False
182       60     40           2      False
227       55     85           2      False
292       90     65           3      False
344       80     65           3      False
451       70     55           4      False
452      105     90           4      False
603       39     57           5      False
604       79     47           5      False
605       69    112           5      False
651       55     15           5      False
652       80     30           5      False

In [18]:
df.sort_values(['Name','HP'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [19]:
df.sort_values(['Name'])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [20]:
print(df.columns.values)

['#' 'Name' 'Type 1' 'Type 2' 'HP' 'Attack' 'Defense' 'Sp. Atk' 'Sp. Def'
 'Speed' 'Generation' 'Legendary']

In [22]:
col = df.columns.values
print (col)

['#' 'Name' 'Type 1' 'Type 2' 'HP' 'Attack' 'Defense' 'Sp. Atk' 'Sp. Def'
 'Speed' 'Generation' 'Legendary']

In [31]:
df1=df.loc[df[:,['HP','Attack']]]

InvalidIndexError: (slice(None, None, None), ['HP', 'Attack'])

In [37]:
import openpyxl
df.to_excel("my-spreadsheet.xlsx",sheet_name="passengers",index=False)

In [40]:
col2=df.columns.values

In [42]:
print(col2)

['#' 'Name' 'Type 1' 'Type 2' 'HP' 'Attack' 'Defense' 'Sp. Atk' 'Sp. Def'
 'Speed' 'Generation' 'Legendary']

In [60]:
df2=df.loc[:,['Name','Defense']]
df3=df.loc[:,['Defense']]
df4=df['Type 2']

In [56]:
print(df2.shape)
print(df2.head(8))

(800, 2)
                        Name  Defense
0                  Bulbasaur       49
1                    Ivysaur       63
2                   Venusaur       83
3      VenusaurMega Venusaur      123
4                 Charmander       43
5                 Charmeleon       58
6                  Charizard       78
7  CharizardMega Charizard X      111

In [66]:
#df2.info();
print(type(df3));
print(type(df4))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [80]:
df5=df[df['#'] == max (df['#'])]
df6=df['#']
df7=df[['#']]

In [78]:
print(type(df5));
print(type(df6));
print(type(df7))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [71]:
print(df5.shape);#print(df6.shape)

(1, 12)